spring.application.name=gof

spring.datasource.url=jdbc:postgresql://localhost:5432/gof
spring.datasource.username=admin
spring.datasource.password=password

# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ignorar o bloqueio estrito de roteamento do Actuator/Swagger no Spring 4.x (prevenção de conflitos)
spring.mvc.pathmatch.matching-strategy=ant_path_matcher